### ISSUE TITLE
How to convert network output to midi or wav file?

### ISSUE THREAD

**Issue by CalmDownForever** [salu133445/musegan#54] opened 2018-12-03 04:39 UTC
Hi, I'm wondering how to get the midi or wav file from the original generator output. So, are there any codes for that. If it is confidential, could you show me some reference to realize that? I‘d appreciate of that.

**Comment by salu133445** [comment] 2018-12-03 08:49
Please refer to #49. Close this issue as it is a duplicate of #49.

**Closed by salu133445** 2018-12-03 08:49 UTC
